name: OANDA 1m Bot

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          OANDA_API_KEY:     ${{ secrets.OANDA_API_KEY }}
          OANDA_ACCOUNT_ID:  ${{ secrets.OANDA_ACCOUNT_ID }}
        run: python bot.py

